name: Docker Image CI

on:
  push:
    branches: 
      - '*'
      - '!master'   # excludes master

  pull_request:
    branches:  
      - '*' 
      - '!master'   # excludes master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t docker.pkg.github.com/${{ github.repository }}/turn:${{ github.sha }} .  

  hello:
    runs-on: ubuntu-latest
    container: hello-world:latest

    steps:
    - uses: actions/checkout@v2
    - name: dir
      run: ls 

  test:
    runs-on: ubuntu-latest
    container: gcr.io/gcp-runtimes/container-structure-test:latest

    steps:
    - uses: actions/checkout@v2
    - name: Run the structure tests
      run: /container-structure-test test --image turn --config ./test_turn.yaml

