name: Docker Image CI

on:
  push:
    branches: 
      - '*'
      - '!master'   # excludes master

  pull_request:
    branches:  
      - '*' 
      - '!master'   # excludes master

jobs:

  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t docker.pkg.github.com/${{ github.repository }}/turn:${{ github.sha }} .  
  
    - name: run structure tests
      uses: plexsystems/container-structure-test-action@v0.1.0
      with:
        image: docker.pkg.github.com/${{ github.repository }}/turn:${{ github.sha }}
        config: test_turn.yaml
