name: Docker Image CI

on:
  push:
    branches: 
      - '*'
      - '!master'   # excludes master

  pull_request:
    branches:  
      - '*' 
      - '!master'   # excludes master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t docker.pkg.github.com/${{ github.repository }}/turn:${{ github.sha }} .  

          
