name: Docker Image CI

on:
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t docker.pkg.github.com/${{ github.repository }}/turn:${{ github.sha }} .  
  
    - name: run structure tests
      uses: plexsystems/container-structure-test-action@v0.1.0
      with:
        image: docker.pkg.github.com/${{ github.repository }}/turn:${{ github.sha }}
        config: test_turn.yaml
        
    - name: Push the Docker image to github packages
      run: |
          echo ${{ github.token }} | docker login docker.pkg.github.com -u chrisguest75 --password-stdin 
          docker push docker.pkg.github.com/${{ github.repository }}/turn:${{ github.sha }}

    - name: Push the Docker image to DockerHub
      run: | 
          echo ${{ secrets.dockerhub }} | docker login --username chrisguest --password-stdin 
          docker tag docker.pkg.github.com/${{ github.repository }}/turn:${{ github.sha }} chrisguest/turn:${{ github.sha }}
          docker push chrisguest/turn:${{ github.sha }}
          docker tag docker.pkg.github.com/${{ github.repository }}/turn:${{ github.sha }} chrisguest/turn:latest
          docker push chrisguest/turn:latest
          
